[versions]
agp = "8.8.0"
kotlin = "1.9.23"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2024.04.01"
retrofit = "2.9.0"
glide = "4.16.0"
firebase-bom = "32.7.0"
firebase-firestore = "24.10.2"
google-services = "4.4.0"
ksp = "1.9.10-1.0.13"
composePlugin = "1.5.11"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version = "1.0.0" }
room-runtime = { module = "androidx.room:room-runtime", version = "2.6.1" }
room-compiler = { module = "androidx.room:room-compiler", version = "2.6.1" }
room-ktx = { module = "androidx.room:room-ktx", version = "2.6.1" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
retrofit2_converter_gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide_compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version = "24.10.3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
